main: os_program1.c test1.c test2.c test3.c test4.c test5.c
	gcc os_program1.c -o prog1
	gcc test1.c -o test1
	gcc test2.c -lm -o test2
	gcc test3.c -o test3
	gcc test4.c -o test4
	gcc test5.c -o test5

clean:
	rm prog1 test1 test2 test3 test4 test5

run_3:
	./prog1 3 ./test1 ./test2 ./test3 ./test4 ./test5

run_6:
	./prog1 6 ./test1 ./test2 ./test3 ./test4 ./test5
	
run_10:
	./prog1 10 ./test1 ./test2 ./test3 ./test4 ./test5


